openapi: 3.0.0
info:
  title: Gaggiuino API
  description: API for managing espresso shots and profiles.
  version: 1.0.0
servers:
  - url: http://gaggiuino.local
paths:
  /api/shots:
    post:
      summary: Log Espresso Shot
      responses:
        "200":
          description: Shot logged successfully
  /api/shots/latest:
    get:
      summary: Get Latest Shot
      responses:
        "200":
          description: Returns the latest shot identifier
  /api/shots/{id}:
    get:
      summary: Get Shot Data
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the shot
          schema:
            type: string
      responses:
        "200":
          description: Returns shot data
  /api/profiles/all:
    get:
      summary: Get All Profiles
      responses:
        "200":
          description: Returns all available profiles
  /api/profile-select/{profileId}:
    post:
      summary: Select Profile
      parameters:
        - name: profileId
          in: path
          required: true
          description: The ID of the profile to select
          schema:
            type: string
      responses:
        "200":
          description: Profile selected successfully
    delete:
      summary: Delete Profile
      parameters:
        - name: profileId
          in: path
          required: true
          description: The ID of the profile to delete
          schema:
            type: string
      responses:
        "200":
          description: Profile deleted successfully
  /api/system/status:
    get:
      summary: Get System Status
      responses:
        "200":
          description: Returns system status
